# Generated by Django 4.2.3 on 2023-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('medecin', models.CharField(max_length=30)),
                ('constante', models.CharField(blank=True, max_length=30, null=True)),
                ('prescription', models.TextField(blank=True, max_length=2000, null=True)),
                ('diagnostique', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institut', models.CharField(max_length=20)),
                ('center_name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('budget', models.DateField(max_length=10)),
                ('state', models.CharField(max_length=3)),
                ('owner', models.DateField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
