# Generated by Django 4.2.3 on 2023-08-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='budget',
            field=models.CharField(max_length=10),
        ),
    ]
