# Generated by Django 4.2.3 on 2023-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_projects_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.CharField(max_length=10),
        ),
    ]
