# Generated by Django 4.2.3 on 2023-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_acteur_satut_remove_acteur_speudo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='DiplomeRequirement',
            new_name='Diplome_Requirement',
        ),
        migrations.RenameField(
            model_name='joboffer',
            old_name='dateAppelOffre',
            new_name='date_Appel_Offre',
        ),
        migrations.RenameField(
            model_name='joboffer',
            old_name='nbreperson',
            new_name='nbre_person',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='typepiece',
        ),
        migrations.AddField(
            model_name='habitant',
            name='type_piece',
            field=models.CharField(choices=[('Cart_National_Identity', 'CNI'), ('Extrait_Naissance', 'EN'), ('Attestation_Identity', 'AI'), ('Carte_Etudiant', 'CE'), ('Autre', 'Autre')], default='Autre', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acteur',
            name='statut',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateurs'), ('RESPONSABLE', 'Responsables'), ('MEMBER', 'Membres')], max_length=30, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='communauty',
            name='localisation',
            field=models.CharField(blank=True, choices=[('Entre_Village', 'Entre du Village'), ('Sortie_Village', 'Sortie du Village'), ('Arbe_Palabre', 'Arbe Palabre'), ('Centre_Village', 'Centre du Village')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='work_space',
            field=models.CharField(choices=[('Entre_Village', 'Entre du Village'), ('Sortie_Village', 'Sortie du Village'), ('Arbe_Palabre', 'Arbe Palabre'), ('Centre_Village', 'Centre du Village')], max_length=20),
        ),
    ]
