# Generated by Django 4.2.3 on 2023-07-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_rename_diplomerequirement_joboffer_diplome_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitant',
            name='work_space',
            field=models.CharField(blank=True, choices=[('Entre_Village', 'Entre du Village'), ('Sortie_Village', 'Sortie du Village'), ('Arbe_Palabre', 'Arbe Palabre'), ('Centre_Village', 'Centre du Village')], max_length=20),
        ),
    ]
