# Generated by Django 4.2.3 on 2023-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_rename_end_date_carnetsante_date_recorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='type_recensement',
            field=models.CharField(choices=[('Inscription', 'Inscription'), ('Amenagement', 'Amenagement'), ('Demenagement', 'Sortie du Village'), ('Naissance', 'Naissance'), ('Décès', 'Décès')], default='Inscription', max_length=20),
            preserve_default=False,
        ),
    ]
