# Generated by Django 4.2.3 on 2023-08-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_habitant_type_recensement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recensement', models.CharField(choices=[('inscription', 'inscription'), ('amenagement', 'amenagement'), ('demenagement', 'demenagement'), ('naissance', 'naissance'), ('deces', 'deces')], max_length=20)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('father_fullname', models.CharField(max_length=50, null=True)),
                ('mother_fullname', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(max_length=20)),
                ('work_name', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('envent_date', models.DateField(blank=True, null=True)),
                ('event_space', models.CharField(blank=True, max_length=50)),
                ('personal_home', models.CharField(blank=True, max_length=50)),
                ('statut_recensement', models.CharField(blank=True, choices=[('validated', 'validated'), ('refused', 'refused'), ('waiting', 'waiting')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('services', models.CharField(max_length=50, null=True)),
                ('specificity', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('work_space', models.CharField(blank=True, max_length=20)),
                ('payement_code', models.CharField(blank=True, max_length=20)),
                ('statut_recensement', models.CharField(blank=True, choices=[('validated', 'validated'), ('refused', 'refused'), ('waiting', 'waiting')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='habitant',
            name='type_recensement',
            field=models.CharField(choices=[('inscription', 'inscription'), ('amenagement', 'amenagement'), ('demenagement', 'demenagement'), ('naissance', 'naissance'), ('deces', 'deces')], max_length=20),
        ),
    ]
