# Generated by Django 4.2.3 on 2023-08-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_recensement_service_alter_habitant_type_recensement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recensement',
            old_name='envent_date',
            new_name='event_date',
        ),
    ]
