# Generated by Django 4.2.3 on 2023-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_rename_envent_date_recensement_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='specificity',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
