# Generated by Django 4.2.3 on 2023-08-17 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_service_specificity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitant',
            old_name='installation_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='deathdate',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='neighborhoodmove',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='read_ability',
        ),
        migrations.AddField(
            model_name='habitant',
            name='event_space',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='habitant',
            name='father_fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habitant',
            name='mother_fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habitant',
            name='personal_home',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='habitant',
            name='sexe',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitant',
            name='statut_recensement',
            field=models.CharField(blank=True, choices=[('validated', 'validated'), ('refused', 'refused'), ('waiting', 'waiting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='type_recensement',
            field=models.CharField(choices=[('amenagement', 'amenagement'), ('demenagement', 'demenagement'), ('naissance', 'naissance'), ('deces', 'deces')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='work_name',
        ),
        migrations.AlterField(
            model_name='recensement',
            name='type_recensement',
            field=models.CharField(choices=[('amenagement', 'amenagement'), ('demenagement', 'demenagement'), ('naissance', 'naissance'), ('deces', 'deces')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ReferentielMetier',
        ),
        migrations.AddField(
            model_name='habitant',
            name='work_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
