# Generated by Django 4.2.4 on 2023-08-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_rename_installation_date_habitant_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteur',
            name='HabitantID',
        ),
    ]
